### ISSUE TITLE
How does secrets.yml work?

### ISSUE THREAD

**Issue by FaultyFunctions** [Konstanius/MineCICD#17]
I might not be understanding what secrets.yml does exactly. Could I get a more concrete example of what it is supposed to do? Does it replace the key on pull? Does it replace it on push to the repo?

**Comment by Konstanius** [comment]
It makes it so that the secret is masked (hidden) in your repository, but shown in your server installation. When pushing, it replaces it with the mask, and when pulling replaces it again.

The latest secrets.yml is pretty detailed in describing how it works, please see https://github.com/Konstanius/MineCICD/blob/master/src/main/resources/secrets.yml
