### ISSUE TITLE
[Feature] Secrets 

### ISSUE THREAD

**Issue by darksaid98** [Konstanius/MineCICD#6]
Not sure whether this is completely out of scope or not for the plugin, but a major holdback for me using this is the fact that there is no way to define server-specific configuration. 

I mean this in the sense of sensitive data like database details, specific server names, port configurations, and other such details I wouldn't want to expose in a repository. 

I'm not sure what the best solution would be, (*or what's even feasible considering other plugins may load before MineCICD*). My wish would be to provide something like a `.env` file that replaces variables in a set of specific files. (*and that before said plugins load their configurations*). This would allow users to put something like `{{MINECICD_SECRET_DATABASE_PASSWORD}}` into a config but have it replaced on startup.

I'm not even sure what the best way would then be to revert said changes. Apologies if this was a bit of an incoherent rant, just a cool feature I'd love to have.

**Comment by Konstanius** [comment]
Will try to implement this using Git native smudge and clean filtering.

**Comment by Konstanius** [comment]
This will definitely be an opt-in feature for per-file, per-secret replacements.

The plugin itself is designed to allow modification of any data from remote.

For insight into how this feature will be implemented:
- There will be a `secrets.yml` file in the `plugins/MineCICD/` directory
- This will allow specifying the files and their respective secrets to replace with the given placeholder.
- This file will probably not be editable via ingame commands, keeping security for it.

Will have to experiment with possible security flaws, since the .gitignore is modifiable from remote, possibly allowing an authorized remote actor to add the secrets file to git tracking

**Comment by Konstanius** [comment]
Currently only being held back by Git's filtering, which runs any executable to filter a STDIN to a STDOUT, transforming the secrets / variables.

Issue is, that `sed`, which is normally used on Linux in combination with Git, doesnt usually work on Windows (It works on my Windows dev machine, but not my Windows test server).

Will troubleshoot further and release, once ready.

Any help welcome for this:

/.git/config
```
[filter "plugins/bStats/config.yml"]
	clean = sed -e 's/571456f9-eb12-4798-989e-4bc16300e4ff/{{server_uuid}}/g' 
	smudge = sed -e 's/{{server_uuid}}/571456f9-eb12-4798-989e-4bc16300e4ff/g' 
```
Will produce, on Windows:
```
Execution of filter command 'sed -e 's/571456f9-eb12-4798-989e-4bc16300e4ff/{{server_uuid}}/g'' on file 'plugins/bStats/config.yml' failed with return code '1', message on stderr: 'Der Befehl "sed" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.'
```

**Comment by Konstanius** [comment]
Might've gone a bit overkill, but now included a primitive native port of `sed` written in Dart in the resource, which will be triggered within the filters if `sed` is not detected.

MineCICD Version 2.1-Release contains the feature you requested, thank you for the idea.
Please provide further feedback you may have during using it.

**Comment by darksaid98** [comment]
Splendid! I went for a nap and a walk and this not-so-tiny feature is already implemented. My thanks to you, I'll be trying it out shortly and will let you know of any issues I run into.

**Comment by darksaid98** [comment]
> Might've gone a bit overkill, but now included a primitive native port of `sed` written in Dart in the resource, which will be triggered within the filters if `sed` is not detected.

Also, yea I'd say it's completely reasonable as installing sed on Windows would be quite painful for the common user.

**Comment by Konstanius** [comment]
The problem is not in that it would need sed to work. Theoretically, a simple powershell or cmd script should be able to do something similar to `sed`.

The issue is, that no matter how much I iterated through versions of Powershell commands, the output was always empty. Therefore I chose this solution, which should 100% work afaik.
